### ISSUE TITLE
Support for orthogonal indexing

### ISSUE THREAD

**Issue by will133** [TileDB-Inc/TileDB-Py#103]
I ran this on TileDB-py 0.3.0 with TileDB 1.4.0.

It seems like the slicing operation from an SparseArray or a DenseArray would only support queries such as:

a[1, 30:40]

However, if I have a list of values to query (say 1, 4, 10), it would fail:

a[[1, 4, 10], 30:40]

The only way I can think of doing this is to iterate through the list and do a slice like:

a[1, 30:40]
a[4, 30:40]
a[10, 30:40]

Is there a more efficient to do this?  I'd imagine doing this in python would be pretty slow.  If I have more dimensions it can get more complicated.  For instance, if I know the exact index for the things I want to query say for a 3d array:

a[[1, 4, 10], [20, 30, 40], 30:40]

Then I have to get the cartesian  production of [1, 4, 10] and [20, 30, 40] and slice through the rest.

In zarr for instance, there's a special function to do this  (https://zarr.readthedocs.io/en/stable/tutorial.html#orthogonal-indexing).  Do you see this is a viable option to implement in TileDB?

**Comment by jakebolewski** [comment]
@will133  you are right in that orthogonal indexing is not supported (currently). In core TIleDB this issue is tracked by https://github.com/TileDB-Inc/TileDB/issues/675.  We could implement a solution similar to Zarr, but this would degenerate into multiple different subqueries to TileDB.  Pushing this to TileDB would enable us to do it in a more efficient way, but there is no technical reason why we could not at least match Zarr here (in Zarr the performance is probably acceptable, but not great).

**Comment by will133** [comment]
It seems like the multi-array reading in the C++ library is implemented and marked as resolved.  Do you know what's the plan of implementing this on the python side?

**Comment by jakebolewski** [comment]
Hi @will133, we do plan to support incorporate these changes in the next version of TileDB / TileDB-PY.  This feature was a lot of work!  (it was developed under the constraint of supporting 10M+ range queries at once on a 100 TB uncompressed array).

**Comment by will133** [comment]
Sounds impressive!  Thanks for all the hard work!

**Comment by jakebolewski** [comment]
The proposed API will follow the spec. in the following NEP https://www.numpy.org/neps/nep-0021-advanced-indexing.html#nep-21-simplified-and-explicit-advanced-indexing, as Numpy only supports vectorized indexing.  TileDB does not currently support vectorized indexing (so only `Array.oindex` will be provided for now).

**Comment by bkmartinjr** [comment]
@jakebolewski - do you have an updated estimate of when more advanced indexing will be available in the Python library?  TY!

**Comment by ihnorton** [comment]
Hi @bkmartinjr, multi-range/orthogonal slicing (https://docs.tiledb.io/en/stable/tutorials/reading.html#multi-range-subarrays) will be available in TileDB-Py by Mon or Tue next week.

**Comment by bkmartinjr** [comment]
Thanks @ihnorton - that made my day!  Will they be released to PyPi at that time, or just landed to master?

**Comment by ihnorton** [comment]
I'm not sure about a release, but I can definitely provide linux wheels built against master.
