### ISSUE TITLE
`pip install tiledb` does not install `native` directory on macOS

### ISSUE THREAD

**Issue by kyungminlee** [TileDB-Inc/TileDB-Py#105]
I don't have `tiledb` installed separately on my macOS. Using `miniconda3-latest` using `pyenv`, with python version 3.6, I install `tiledb-py` through `pip install tiledb`.

```
$ python -m tiledb
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/site-packages/tiledb/__init__.py", line 16, in <module>
    ctypes.CDLL(os.path.join(lib_dir, lib_name))
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/user/.pyenv/versions/py36/lib/python3.6/site-packages/tiledb/native/libtiledb.dylib, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/site-packages/tiledb/__init__.py", line 19, in <module>
    ctypes.CDLL(lib_name)
  File "/Users/user/.pyenv/versions/py36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libtiledb.dylib, 6): image not found

$ ls /Users/user/.pyenv/versions/py36/lib/python3.6/site-packages/tiledb
__init__.py                     __pycache__                     libtiledb.cpython-36m-darwin.so tests                           version.py
```

[install-tiledb-log.txt](https://github.com/TileDB-Inc/TileDB-Py/files/2780649/install-tiledb-log.txt)

**Comment by tdenniston** [comment]
It looks like the wheel is not being built by pip (no `bdist_wheel` was run according to your log). Could you first try explicitly installing the `wheel` package before TileDB? E.g. `pip uninstall tiledb && pip install wheel && pip install tiledb`.

If that doesn't work could you please try `pip install tiledb --no-cache-dir`?

**Comment by kyungminlee** [comment]
I have wheel 0.32.3 installed through conda (as you can see in line 38), and I did use `pip install tiledb --no-cache-dir`.

**Comment by ihnorton** [comment]
There is a bug in pip which causes `--no-cache-dir` to skip `bdist_wheel`, which means that the native library isn't built: https://github.com/pypa/pip/issues/5749

TileDB-Py 0.3.1 was just released, so `pip install tiledb` should do a fresh build. If you need to avoid the cache, specifying a *different* cache should work and will force a clean build: `pip install --cache-dir=/PATH/TO/mycache tiledb`. Or you can [remove the global pip cache](https://stackoverflow.com/a/31807659/508431).

We also have [conda packages](https://anaconda.org/conda-forge/tiledb-py) available on all platforms.

Hopefully the above helps so I will close this -- please comment if this is still and issue and we can reopen.

**Comment by ihnorton** [comment]
> If you need to avoid the cache, specifying a *different* cache should work and will force a clean build: `pip install --cache-dir=/PATH/TO/mycache tiledb`

Hmm, actually this appears to have failed in the same way. So I guess the only option to force a clean build right now is to delete your cache. I just tested `pip install tiledb` in a clean environment and it worked correctly.
