### ISSUE TITLE
Make the uri property of tiledb.Array public

### ISSUE THREAD

**Issue by chineking** [TileDB-Inc/TileDB-Py#117]
We are developing a distributed tensor-based system called [Mars](https://github.com/mars-project/mars), and we decided to add an external storage API. We considered to [support tiledb from scratch](https://github.com/mars-project/mars/issues/219).

Our approach is that either the tiledb Array or ctx as well as uri can be provided to create a Mars tensor. and we will also tile the tensor into chunks which we be executed on different workers.

But a tiledb Array's uri property is not public/readonly in cython, so if a tiledb Array is passed to Mars tensor, the uri of the array cannot be obtained, and also this array cannot be serialized, thus we cannot send the uri to the workers to write or read tiledb Array in parallel.

Maybe just make the uri property public is a solution?

**Comment by ihnorton** [comment]
Hi @chineking, thanks for the suggestion. Fixed in #117. Mars looks like an interesting project, and we are happy to learn that you are considering TileDB.
