### ISSUE TITLE
QueryCondition with leading whitespace throws error

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#1396]
If a QueryCondition has leading white space, the QueryCondition parser will throw an error.    It does not seem sensitive to intermediate or trailing white space.

Ideally, it would ignore all whitespace including NL, allowing multi-line strings, eg, in Python:
```
qc = tiledb.QueryCondition("""
         a == 'a'
      and
        b == 'b'
    """)
```

Example failure running TileDb-Py 0.17.5:
```
In [34]: tiledb.QueryCondition("a == 'a'")
Out[34]: QueryCondition(expression="a == 'a'")

In [35]: tiledb.QueryCondition(" a == 'a'")
---------------------------------------------------------------------------
IndentationError                          Traceback (most recent call last)
File ~/projects/soma-scratch/venv/lib/python3.10/site-packages/tiledb/query_condition.py:115, in QueryCondition.__post_init__(self)
    114 try:
--> 115     self.tree = ast.parse(self.expression, mode="eval")
    116 except:

File /usr/lib/python3.10/ast.py:50, in parse(source, filename, mode, type_comments, feature_version)
     49 # Else it should be an int giving the minor version for 3.x.
---> 50 return compile(source, filename, mode, flags,
     51                _feature_version=feature_version)

IndentationError: unexpected indent (<unknown>, line 1)

During handling of the above exception, another exception occurred:

TileDBError                               Traceback (most recent call last)
Cell In [35], line 1
----> 1 tiledb.QueryCondition(" a == 'a'")

File <string>:5, in __init__(self, expression, ctx)

File ~/projects/soma-scratch/venv/lib/python3.10/site-packages/tiledb/query_condition.py:117, in QueryCondition.__post_init__(self)
    115     self.tree = ast.parse(self.expression, mode="eval")
    116 except:
--> 117     raise tiledb.TileDBError(
    118         "Could not parse the given QueryCondition statement: "
    119         f"{self.expression}"
    120     )
    122 if not self.tree:
    123     raise tiledb.TileDBError(
    124         "The query condition statement could not be parsed properly. "
    125         "(Is this an empty expression?)"
    126     )

TileDBError: Could not parse the given QueryCondition statement:  a == 'a'
```

**Comment by nguyenv** [comment]
Thank you for reporting this. I've filled this in our issue tracker.

**Comment by bkmartinjr** [comment]
FYI: I just noticed it will also error out if there is a newline in the middle of the query condition.

**Comment by nguyenv** [comment]
For background info, we parse query conditions under the hood using Python's AST module, so it does take into account leading whitespaces and newlines like it does for Python source code. I will put some more thought about how we should clean the query condition prior to running it through parser, but it sounds like we at least need to `.strip()` and to remove trailing white space and `\t` and `\n` characters.

**Comment by bkmartinjr** [comment]
Ah, that explains the issue - Python syntax has a lot of whitespace sensitivity.

I haven't given this deep consideration, but simply doing the following seems like it should work:
* strip leading & trailing white space
* replace all white space runs, which are outside a quoted string, with a single ASCII space

**Comment by johnkerl** [comment]
> but it sounds like we at least need to .strip() and to remove trailing white space and \t and \n characters.

@nguyenv not remove but replace with a space i think -- otherwise non-syntactical

```
a
b < 10
```

would become syntactical

```
ab < 10
```

**Comment by nguyenv** [comment]
Sorry I had written that paragraph on my phone while I was out yesterday, but I had meant with that sentence that we needed to remove padded whitespace and to properly handle any embedded newline and tabs beforehand. But with the PR I just put in, I was able to get the AST parser to just handle all these issues for us without needing to do it ourselves.

**Comment by bkmartinjr** [comment]
@nguyenv - quick question. I had assumed the C++ layer was doing the parsing, i.e., there was a common parser in the TileDB Embedded C++ core.  If not the case, and each language binding (R, Python, ...) implements its own, is there filter syntax/operator compatibility between these environments?  TY!

**Comment by nguyenv** [comment]
https://github.com/TileDB-Inc/TileDB/blob/dev/examples/cpp_api/query_condition_dense.cc#L292-L296

All the APIs use the C++ `QueryCondition` class which defines comparison operators `TILEDB_EQ`, `TILEDB_LT`, `TILEDB_GT`, etc. and Boolean operators `TILEDB_AND` and `TILEDB_OR`. The core team has written an underlying AST that handles the correct order of operations for the AND and OR combines.

**Comment by johnkerl** [comment]
Thanks @nguyenv ! I think an open question is how `tiledb-r` and `tiledbsoma-r` handle similar whitespacing issues -- and we should check with @aaronwolen and @eddelbuettel .

But a quick check with `tiledbsoma-r` looks good:

```
> sdf <- SOMADataFrame$new("/Users/johnkerl/s/v/pbmc-small/obs")=

See $metadata for additional Schema metadata
> sdf$read(value_filter='   groups == "g1"    ')
Table
44 rows x 8 columns <---------------- note
$obs_id <string>
$orig.ident <int32>
$nCount_RNA <double>
$nFeature_RNA <int32>
$RNA_snn_res.0.8 <int32>
$letter.idents <int32>
$groups <string>
$RNA_snn_res.1 <int32>

> sdf$read(value_filter='   groups == "g2"    ')
Table
36 rows x 8 columns <---------------- note
$obs_id <string>
$orig.ident <int32>
$nCount_RNA <double>
$nFeature_RNA <int32>
$RNA_snn_res.0.8 <int32>
$letter.idents <int32>
$groups <string>
$RNA_snn_res.1 <int32>
```

**Comment by eddelbuettel** [comment]
Every implementation has its own one-off parser.  Which is not great.  Which is why I have been on record for a bit as suggesting the parser should  indeed be an API feature just as @bkmartinjr surmised it would be.
