### ISSUE TITLE
PyPI wheels for macOS

### ISSUE THREAD

**Issue by tdenniston** [TileDB-Inc/TileDB-Py#144]
Currently we distribute wheels for `manylinux`. It'd be nice to also distribute wheels for macOS.

**Comment by ihnorton** [comment]
This project is still pretty new, but I'm hoping it might eventually let us do wheels from conda builds: https://github.com/regro/conda-press

**Comment by tdenniston** [comment]
We could also check out https://github.com/MacPython/numpy-wheels for inspiration.

**Comment by ihnorton** [comment]
conda-press just had an initial release. I tried it out, and it looks promising, with a few relatively minor fixes: https://github.com/regro/conda-press/pull/16
