### ISSUE TITLE
Multidimensional variable length array write fails

### ISSUE THREAD

**Issue by noormichael** [TileDB-Inc/TileDB-Py#170]
I got an exception running the following code. I am using Python 3.6.6, TileDB version 1.5.1 and TileDB-Py version 0.4.2 on Linux.

```
import numpy as np
import tiledb

array_name = 'example_array'
ctx = tiledb.Ctx()

dom = tiledb.Domain(tiledb.Dim(name="rows", domain=(0, 1), tile=2, dtype=np.int64),
                    tiledb.Dim(name="cols", domain=(0, 1), tile=2, dtype=np.int64), ctx=ctx)

schema = tiledb.ArraySchema(domain=dom, sparse=False,
                            attrs=[tiledb.Attr(name="a", dtype='S', ctx=ctx)],
                            ctx=ctx)

tiledb.DenseArray.create(array_name, schema)

with tiledb.DenseArray(array_name, mode='w', ctx=ctx) as A:
    A[...] = np.array([['A', 'B'], ['A', 'B']], dtype='S')
```

```
Traceback (most recent call last):
  File "./tiledb_example.py", line 17, in <module>
    A[...] = np.array([['A', 'B'], ['A', 'B']], dtype='S')
  File "tiledb/libtiledb.pyx", line 4394, in tiledb.libtiledb.DenseArray.__setitem__
  File "tiledb/libtiledb.pyx", line 4465, in tiledb.libtiledb.DenseArray._write_dense_subarray
  File "tiledb/libtiledb.pyx", line 250, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 235, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::Writer] Error: Buffer sizes check failed; Invalid number of cells given for attribute 'a' (2 != 4)
```

It seems like 2D numpy string arrays don't work with multidimensional dense arrays. Looking at the call to `_pack_varlen_bytes(self, object val)`, the for loops that iterate through `val` (`np.ndarray arr`) don't loop through the individual elements in the multidimensional case. https://github.com/TileDB-Inc/TileDB-Py/blob/ac9ab44d63d54e3fcab22dad00a226dddb977573/tiledb/libtiledb.pyx#L3713-L3723 
https://github.com/TileDB-Inc/TileDB-Py/blob/ac9ab44d63d54e3fcab22dad00a226dddb977573/tiledb/libtiledb.pyx#L3750-L3758 Iterating through a multidimensional array returns the corresponding subarrays, not the individual elements. Therefore the buffer offsets don't correspond to individual elements, but subarrays of the original array. Do you think it should iterate through this array using `arr.flatiter`, which loops through the individual elements?

**Comment by ihnorton** [comment]
@noormichael I just merged a fix in #194, including a test based on your example, and some related tests and fixes. Thanks for the bug report and reproduction.
