### ISSUE TITLE
ignore deprecated C API warnings when cythonizing / building extension lib 

### ISSUE THREAD

**Issue by jakebolewski** [TileDB-Inc/TileDB-Py#175]
We need to support deprecated C api's to preserve backwards compatibility, these should be turned off by passing the appropriate compilation flag.

**Comment by ihnorton** [comment]
Are you getting an error, or do you want to suppress the warnings? AFAICT the defaults don't enable `Werror` on mac (builds fine for me, with deprecation warnings)

**Comment by jakebolewski** [comment]
It builds, but the warnings here are not very relevant as we know that these api's are deprecated.  This is not pressing IMO, just it might be a little disconcerting to have a wall of warnings show up when building from source.
