### ISSUE TITLE
Creating Domains

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#177]
Domains need to be of the same datatype atm. I need a flaot64 and a datetime64 domain which is not possible if i am correct.
Not sure if this is by design or if having multiple datatypes is just a missing feature.

**Comment by stavrospapadopoulos** [comment]
Hello Arne. This is a missing feature tracked by [this issue](https://github.com/TileDB-Inc/TileDB/issues/93), which we just started working on. It is scheduled for 1.7, hopefully by end of the summer.

**Comment by ihnorton** [comment]
Please see example added in https://github.com/TileDB-Inc/TileDB-Py/pull/305
