### ISSUE TITLE
Query by attributename

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#178]
It would be convenient if querying by attribute would be a thing for multi domain databases.
```python
with tiledb.SparseArray(dbname+".tiledb", mode='r') as A:
    A.dump() 
    A.query(attrs=("some_attribute",))[date=[np.float64(pd.Timestamp('2014-01-22T12:00:00').value).item():np.float64(pd.Timestamp('2014-01-22T13:00:00').value).item()]]["some_attribute"]

**Comment by ihnorton** [comment]
Hi @aosterthun, I am reviewing some issues here and wanted to check in on this one -- could you explain more (if you remember) what the goal was here? The `query(attrs=("some_attribute"),))...` invocation should work fine. See [here](https://github.com/TileDB-Inc/TileDB-Py/blob/dev/tiledb/tests/test_libtiledb.py#L1100-L1117).

**Comment by ihnorton** [comment]
Please comment and reopen if needed.
