### ISSUE TITLE
SparseArray.subarray() doesn't render the docs in Sphinx

### ISSUE THREAD

**Issue by jakebolewski** [TileDB-Inc/TileDB-Py#182]
Sphinx renders the docs for DenseArray.subarray() but not for SparseArray.subarray(), need to investigate.

Also add an example or two to both for usage.

**Comment by ihnorton** [comment]
Were you looking at an older version?

https://docs.tiledb.io/projects/tiledb-py/en/stable/python-api.html#tiledb.SparseArray.subarray
https://docs.tiledb.io/projects/tiledb-py/en/latest/python-api.html
