### ISSUE TITLE
tile parameter ignored in variable length dimensions 

### ISSUE THREAD

**Issue by mbriggs134** [TileDB-Inc/TileDB-Py#1838]
https://github.com/TileDB-Inc/TileDB-Py/blob/f219f165e6cbe983a69166f02e59f97f9e3cd502/tiledb/dimension.py#L56

Per the referenced comment it appears that variable length dimension's tile parameter is ignored.  First is this still true?  Will this be fixed in an upcoming release?

**Comment by ihnorton** [comment]
Hi @mbriggs134, there is no space tiling for var-length dimensions. For string dimensions in particular, sorting is lexical, and the storage tile size is controlled by the array schema `capacity` parameter. See also: https://docs.tiledb.com/main/how-to/arrays/creating-arrays/creating-dimensions

> for string dimensions, the domain and tiling are handled implicitly

And: https://docs.tiledb.com/main/how-to/performance/performance-tips/summary-of-factors#tile-capacity

Hope this helps -- let me know if there is anything we can clarify in the docs, or if you have a use-case that is different from the current behavior. I'll close for now, but happy to reopen if necessary.
