### ISSUE TITLE
tiledb-py > 0.21.6 and corresponding versions of tiledb embedded miss the path separator and query string prefix when utilizing SAS tokens with Azure Blob Storage

### ISSUE THREAD

**Issue by sindhudweep** [TileDB-Inc/TileDB-Py#1844]
OS: Linux
Versions: tiledb-py >= 0.22.0 ; libtiledb >=2.16.0

Versions of tiledb-py > 0.21.6 and corresponding versions of tiledb embedded miss the path separator and query string prefix.

tiledb.cc.TileDBError: C API: TileDB Internal, std::exception; Fail to get a new connection for: https://REDACTED.blob.core.windows.netse=2023-10-11T17%3A30%3A29Z&sp=rwdlt&sv=2023-08-03...

I can work around this by detecting the version of libtiledb, and prepending the sas token with '/?'

```
def _should_infix_separator_and_get_params_for_new_TileDB(semver: Tuple[int, int, int] = None) -> bool:
    threshold = (2, 16, 0)
    return (semver or tiledb.libtiledb.version()) >= threshold

def _get_infix_separator_for_new_TileDB(semver: Tuple[int, int, int] = None) -> str:
    return '/?' if _should_infix_separator_and_get_params_for_new_TileDB(semver) else ''

config["vfs.azure.storage_sas_token"] = _get_infix_separator_for_new_TileDB() + sas_token
```

**Comment by ihnorton** [comment]
Hi @sindhudweep, thanks for opening this issue. We will debug this and get a fix into libtiledb as soon as possible. cc @KiterLuc [sc-35417]
