### ISSUE TITLE
tiledb.walk() hangs indefinitely when blob with folder name exists

### ISSUE THREAD

**Issue by The-Fonz** [TileDB-Inc/TileDB-Py#1845]
In cloud blob storage, there is no concept of a folder, just a concept of a "separator" like `/`. Blobs with the name of your intended folder can exist. When walking a bucket that has a blob with the "folder" name, tiledb.walk() hangs indefinitely.

To reproduce:

tiledb v0.23.1

Bucket with group/array like this:

```
# Nothing wrong here
gs://bucket/group/__tiledb_group.tdb
gs://bucket/group/array/...

# Hangs indefinitely when walking with tiledb.walk("gs://bucket/")
gs://bucket/group/
gs://bucket/group/__tiledb_group.tdb
gs://bucket/group/array/...
```

**Comment by ihnorton** [comment]
Hi @The-Fonz, just to clarify, in the second scenario there is an object called `group`?
```
gs://bucket/group # <- This is an object?
```

**Comment by kounelisagis** [comment]
Hi @The-Fonz, thank you for opening the issue.

After testing the following with `tiledb==0.32.3`:

```
import tiledb

# write a group and array to the cloud
grp_path = "gs://tiledb-agis/group"
tiledb.Group.create(grp_path)

grp = tiledb.Group(grp_path, "w")
array_path = "gs://tiledb-agis/group/array"
domain = tiledb.Domain(tiledb.Dim(domain=(1, 8), tile=2))
a1 = tiledb.Attr("val", dtype="f8")
schema = tiledb.ArraySchema(domain=domain, attrs=(a1,))
tiledb.Array.create(array_path, schema)

grp.add(array_path)
grp.close()

# walk the cloud
def callback(path, type):
    print(path, type)

tiledb.walk("gs://tiledb-agis/", callback)
```

it successfully prints:

```
gs://tiledb-agis/group group
gs://tiledb-agis/group/array array
```

Seems like the issue doesn't exist anymore. Feel free to let us know if you have anything to add.
