### ISSUE TITLE
Locks not removed

### ISSUE THREAD

**Issue by manolinux** [TileDB-Inc/TileDB-Py#189]
Hi,

After manually cancelling (CTRL+C) a script in Python that writes some TileDB arrays, when trying to read again, some locks were not deleted:

Failed to lock 'C:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes\recintos\id6_1_0_24_1076_1\__lock.tdb'; CreateFile error

Is there any way to minimize this problem? For instance, I've tested Zarr arrays before (and my code is an evolution from prior Zarr checks) and those kind of sudden cancels never left abandoned locks behind.

They say they use "fasteners" package for file locking, if this is hint.

Kind regards!

**Comment by ihnorton** [comment]
Hi @manolinux, thanks for opening the issue. I tried to reproduce it on a windows system, and so far could not. The `__lock.tdb` file should always exist, but we hold a lock on a region of the file as needed. The semantics on windows should guarantee that this lock is released when the process exits, although apparently there can be a delay.

All that said, the filename looks different than the lockfiles written by the current TileDB version. Could you let me know what version of python and libtiledb you are using?

**Comment by manolinux** [comment]
Hi, thanks a lot for answering so fast:

import tiledb
tiledb.libtiledb.version()
(1, 5, 1)

installed from Conda ...

Regards!

**Comment by manolinux** [comment]
Hi, updated to TileDB 1.6.0, and this issue seems not to appear.

Thanks and kind regards, I'm closing the issue

**Comment by ihnorton** [comment]
Thanks for the update!
