### ISSUE TITLE
Problems when writing TileDB group

### ISSUE THREAD

**Issue by manolinux** [TileDB-Inc/TileDB-Py#193]
I intend to write to one group, contained in a variable called "grupo_parcela", opening it in write 
mode:
````
with tiledb.SparseArray(grupo_parcela, mode='w') as parcelaAttrsW:
````
grupo_parcela has this value:
````
C:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes\hdf5\tiledb\orellana\recintos\id6_1_0_2_3_1
````
and it has __array_schema.tbd and __lock.tbd file inside

This is the point where the script is launched:
```
C:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes
```

But when I try to write parcelaAttrsW, I get a message complaining about not being able to write file, but the message is referring to launching directory, rather than TileDB group directory.

Any idea of what's going on?

Thanks and kind regards!

```
Traceback (most recent call last):
  File "c:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes\calculo_nn_all_in_one_tiledb.py", line 474, in calculo_nn_all_in_one
    parcelaAttrsW[timestamp] =  {'eto': [etoParcela], 'trigger': [trigger]}
  File "tiledb\libtiledb.pyx", line 4733, in tiledb.libtiledb.SparseArray.__setitem__
  File "tiledb\libtiledb.pyx", line 4793, in tiledb.libtiledb.SparseArray._write_sparse
  File "tiledb\libtiledb.pyx", line 254, in tiledb.libtiledb._raise_ctx_err
  File "tiledb\libtiledb.pyx", line 239, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::IO] Error: Cannot write to file 'c:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes'; File opening error
[TileDB::IO] Error: Cannot write to file 'c:\Users\manuel.cotallo\redarex-python\GEOpexGeoprocessingSystem\2018\GEOpexProcessing\trunk\src\modules\vegetation_module\processes'; File opening error
```

**Comment by ihnorton** [comment]
Hi @manolinux, thanks for opening the issue. I will try a few tests to reproduce on windows today, but if you can share a reduced version of your script to demonstrate the problem that will be helpful. (along the lines of https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by ihnorton** [comment]
Hi @manolinux, I've tried a few small experiments writing to a group, but have not reproduced the error. If you have any test code or snippets you can share, that would be very helpful.

**Comment by manolinux** [comment]
Sorry for the delay,

I've been busy with the numerical calculations of my code, speeding up with
Numba. Now I made it stable (with Zarr), I want to check if I've got speed
gains with TileDB storage.

I'm debugging in Visual Studio, and may tell some more info in a while.

Thanks a lot!

**Comment by manolinux** [comment]
Hi,

Finally I found a way that avoids problem. I was using all the time uri parameter for SparseArray openings, creating, etcetera, with full-path references.

Now I'm using just the final name of the array for creation, opening, etc, and chdir-ing before, and that seems to work.

There seems to be something strange when trying to use full path references, something like

```
with tiledb.SparseArray(path, mode='w') as parcelaAttrsW:
    parcelaAttrsW[timestamp] =  {'eto': [etoParcela], 'trigger': [trigger]}
```` 
makes the array parcelaAttrsW think the directroy for writing is current directory, rather than path, thus failing. 

As that part is in cPython syntax, I've not been able to debug to give you an idea of what really fails, the stacktrace is in a previous message.

So, I'm closing the issue, will add more info if I can dig into the code and determine what may fail.

Thanks a lot for your support and collaboration!
Manuel.
