### ISSUE TITLE
Unable to consolidate via fragment_uris

### ISSUE THREAD

**Issue by kylemann16** [TileDB-Inc/TileDB-Py#1944]
I got a warning that consolidating by timestamp is deprecated, so to work around this I decided to grabbed a list of fragments, filter by their timestamp, and pass that list to consolidate. 

This resulted in the error: `tiledb.cc.TileDBError: [TileDB::Consolidator] Error: Cannot consolidate; Not all fragments could be found`.

- Minimum example and associated logs: https://gist.github.com/kylemann16/67a0825a4f52723a3a43e8688d0b4892
- Expected: Consolidate a list of `fragment_uris`. 
- Reality: Tiledb does not consolidate if you pass a list of uris corresponding to the fragments retrieved from `tiledb.array_fragments`
- Tiledb versions from conda:
```
# Name                    Version                   Build  Channel
tiledb                    2.20.0               h49d9ff7_0    conda-forge
tiledb-py                 0.26.0          py311h422783f_1    conda-forge
```

**Comment by Shelnutt2** [comment]
Hello @kylemann16 we are looking into this and will get back to you soon.

**Comment by ihnorton** [comment]
@kylemann16 sorry, the doc/argument name here is wrong. Right now the API takes only the fragment _name_, not the full path (doc update in #1946, and https://app.shortcut.com/tiledb-inc/story/24097 - cc @KiterLuc). Here's an updated script that works:

```
# https://github.com/TileDB-Inc/TileDB-Py/issues/1944
import tiledb
import numpy as np
import urllib
import os

tdb_dir = 'error.tdb'

dim_row = tiledb.Dim(name="X", domain=(0,10), dtype=np.int32)
dim_col = tiledb.Dim(name="Y", domain=(0,10), dtype=np.int32)
domain = tiledb.Domain(dim_row, dim_col)

z_att = tiledb.Attr(name="Z", dtype=np.int32)
schema = tiledb.ArraySchema(domain=domain, sparse=True,
    attrs=[z_att], allows_duplicates=True)

tiledb.SparseArray.create(tdb_dir, schema)
for x in range(10):
    with tiledb.open(tdb_dir, "w") as a:
        a[x, x] = { 'Z': 10 }

afs = tiledb.array_fragments(tdb_dir)

uris = [
    urllib.parse.urlparse(f).path for f in afs.uri
]
print("uris: ", uris)
for f in uris:
    if not os.path.exists(f):
        print("f is: ", f)
        raise Exception(f)
frag_names = [
    os.path.split(urllib.parse.urlparse(f).path)[-1] for f in afs.uri
]
tiledb.consolidate(tdb_dir, fragment_uris=frag_names)
```
