### ISSUE TITLE
Multiprocessing support

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#197]
I tried to implement multiprocessing for my netCDF ingestion tool. For some reason I can not get tileDB to finish the write call. TileDB seems to write the data but does not return. I use `Process(target=self.ingestChunkWorker, args=(lock, chunkSize, thread_index)).start()` to start my processes and 
```
with tiledb.SparseArray(self.dest_path, mode='w') as A:
    logger.info("Before write")
    A[dim1, dim2, dim3] = np.array(data)
    logger.info("After write")
```
to write to TileDB.

When using Process I never get to `logger.info("After write")`. When using threading.Thread the code works fine. 

Any suggestions ?

**Comment by ihnorton** [comment]
>  When using threading.Thread the code works fine.
> Any suggestions ?

Unfortunately, Intel TBB, which libtiledb uses internally for parallelism, has some issues with `fork`. By default, multiprocessing uses `fork` on mac and linux, but the thread pool and locks don't transfer, causing hangs as you observed. There are some links and further comments in #127.

Changing the multiprocess execution method to `spawn` should work -- here's an example (modified from #127):

```
import multiprocessing as mp

if mp.get_start_method() is None:
    mp.set_start_method('spawn')

from multiprocessing import Pool
import os, shutil
import tiledb, numpy as np

uri = "/tmp/mp1"

if os.path.isdir(uri):
    shutil.rmtree(uri)
ar_small = np.random.rand(10,10)
T = tiledb.from_numpy(uri, ar_small)

def r1(ui):
    uri, idx = ui
    print("in ", os.getpid())
    # works
    ctx = tiledb.Ctx()
    T = tiledb.DenseArray(uri,ctx=ctx)
    return T[idx,idx]

print("applying!")
p = Pool(4)

result = p.map(r1, [(uri,i) for i in range(10)])
print(result)
```

**Comment by ihnorton** [comment]
TileDB core library no longer uses TBB, but the limitations of forking a multi-threaded process are not specific to TBB or TileDB (cf [python docs](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) for example). The `spawn` start method is now the default on macOS, for this reason, and should be used on linux whenever working with multi-threaded libraries as detailed in the example above.

**Comment by ihnorton** [comment]
We've also added an example using multiprocessing, which is regularly run as part of the test suite: https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/parallel_csv_ingestion.py
