### ISSUE TITLE
Querying data with negative real indecies

### ISSUE THREAD

**Issue by aosterthun** [TileDB-Inc/TileDB-Py#201]
Hello there,

I'm working with a TileDB containing to Domains with negative values. When querying values I get:

```
tiledb.libtiledb.TileDBError: [TileDB::Query] Error: Subarray lower bound is larger than upper bound. subarray: [86.75, 86.5, 26.75, 26.75, 157498, 157498] domain: [-89.75, 89.75, -179.75, 179.75, 157498, 157863]
```

My query looks as follows:
```
data = self.data.query(attrs=["some_data"], coords=True)[-3.25,26.75,157498.4375]
```

Also the error message does not display the subarray I define in my query.

**Comment by stavrospapadopoulos** [comment]
We are looking into it, thanks for reporting! It seems that the real values do not properly get passed to `libtiledb`. We will investigate.

**Comment by ihnorton** [comment]
Hi @aosterthun, we are missing support for negative float-domain indexes (https://github.com/TileDB-Inc/TileDB-Py/issues/102). In fact, float slices used to be supported in NumPy, but they [were removed](https://docs.scipy.org/doc/numpy-1.12.0/release.html#deprecationwarning-to-error) in 1.12. So my plan is the following:

- deprecate float slicing directly on Array/SparseArray objects
- add an indexing helper (similar to `oindex` used in several ndarray-like libraries (https://numpy.org/neps/nep-0021-advanced-indexing.html))
- currently intending the following API: `Array.domain_index[...]`, so the slicing in your example above would look like:

```
self.data.domain_index[-3.25,26.75,157498.4375]
```
or with slicing:
```
self.data.domain_index[-3.25,26.75,157498.4375]
```

The semantics will match subarray indexing in the core TileDB library, and the input domain *always* be based on the underlying array domain. I am planning to support full-slice operator `:`, but no wrap-around or steps (at least initially).

I've implemented the above feature on a branch, and will integrate soon (probably 1-2 days).

**Comment by aosterthun** [comment]
Hi,

thank you for fixing that. But could you please send me the branch you comited the feature to ? I can't find it atm.

**Comment by aosterthun** [comment]
I guess it is this (https://github.com/TileDB-Inc/TileDB-Py/tree/ihn/domain_indexing) branch then. I am using TileDB through conda. Can I use the branch as dependency in conda as long as it is not integrated into dev ?

**Comment by ihnorton** [comment]
Hi @aosterthun,

You could build the TileDB-Py source against the core `tiledb` (a.k.a. libtiledb) package from conda with the following steps -- it is only compiling the cython source and extension:

```
conda activate <your environment>
conda install tiledb cython` (note: only `tiledb` here, not `tiledb-py
git clone https://github.com/TileDB-Inc/TileDB-Py
cd TileDB-Py
git checkout ihn/domain_indexing
python setup.py install --tiledb=$CONDA_PREFIX
```
(see also [install instructions](https://github.com/TileDB-Inc/TileDB-Py#building-tiledb-py-against-libtiledb-from-conda))

**Comment by ihnorton** [comment]
Hi @aosterthun, this functionality is now available on the `dev` branch, and we will include it in the next TileDB / TileDB-Py release (in progress: https://github.com/TileDB-Inc/TileDB/pull/1390)

**Comment by aosterthun** [comment]
Thank you. I was ill and on vacation the last few weeks so wasn't able to test this. I'll do this now.

**Comment by aosterthun** [comment]
I was able to build the 0.4.4.dev43 version on TileDB-Py but I can not get my conda environment to use the custom build version for my project.

**Comment by aosterthun** [comment]
push

**Comment by ihnorton** [comment]
Hi @aosterthun there might be a precedence issue if the `tiledb-py` package is already installed in an existing environment. In that case, please `conda uninstall tiledb-py`, and possibly re-run the `setup.py` step in this comment: https://github.com/TileDB-Inc/TileDB-Py/issues/201#issuecomment-534697819
