### ISSUE TITLE
pyproject.toml does not declare all run-time dependencies 

### ISSUE THREAD

**Issue by selimnairb** [TileDB-Inc/TileDB-Py#2031]
Using TileDB-Py 0.31.1, the [packaging](https://pypi.org/project/packaging/) dependency is not declared in `pyproject.toml`, even though it appears to be needed:

```
<snip>
    return pd.DataFrame(A.df[:])
                        ^^^^
  File "libtiledb.pyx", line 1802, in tiledb.libtiledb.Array.df.__get__
  File "/Users/USER/venv/lib/python3.12/site-packages/tiledb/multirange_indexing.py", line 410, in __init__
    check_dataframe_deps()
  File "/Users/USER/venv/lib/python3.12/site-packages/tiledb/dataframe_.py", line 26, in check_dataframe_deps
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

The [conda-forge feedstock](https://github.com/conda-forge/tiledb-py-feedstock/blob/main/recipe/meta.yaml#L45) does declare the `packaging` dependency.

My expectation is that `pyproject.toml` / installation instructions for TileDB-Py would declare all necessary run-time dependencies and that these would match those of the conda-forge feedstock, as I don't normally use conda (especially in containers), and it should not be required to use TileDB-Py.

**Comment by kounelisagis** [comment]
Closed by https://github.com/TileDB-Inc/TileDB-Py/pull/2032
