### ISSUE TITLE
Check version of local libtiledb before using in setup.py

### ISSUE THREAD

**Issue by ihnorton** [TileDB-Inc/TileDB-Py#228]
Related to #227: when an existing libtiledb shared library is detected in setup.py, we should check the version (using ctypes) before using it, and fall back to building from source if it is not compatible.

**Comment by kounelisagis** [comment]
Closing this, as we aim to avoid any incompatibilities between libtiledb and tiledb-py.

- For a very new tiledb-py version and an outdated libtiledb, we use conditions to ensure that the libtiledb version will still work.
- For a very new libtiledb version and an older tiledb-py version, tiledb-py will only use the features available up to that point. libtiledb is not expected to introduce any breaking changes.
