### ISSUE TITLE
data access via tiledb: URI failing for array

### ISSUE THREAD

**Issue by bkmartinjr** [TileDB-Inc/TileDB-Py#242]
I have an array registered with the cloud API which throws an error whenever I access data in the array.  The S3 array object is fine - I can access it directly via S3 using the Python tiledb module.  I can also access its schema via the cloud API, so I know the registered URL is fine. 

Test code below.  I can make the actual array available if it helps debug.

Output and error I see:
```
$ python cloudbug.py
(4, 4) 1 ['a']
OrderedDict([('a', array([1, 2, 3, 4], dtype=int32))])
(33148, 13568) 1 ['']
Traceback (most recent call last):
  File "cloudbug.py", line 20, in <module>
    fetch("tiledb://CZI_Dev/pbmc33k_processed-Xr3zstd_X")
  File "cloudbug.py", line 13, in fetch
    print(A[1])
  File "tiledb/libtiledb.pyx", line 3650, in tiledb.libtiledb.DenseArrayImpl.__getitem__
  File "tiledb/libtiledb.pyx", line 3754, in tiledb.libtiledb.DenseArrayImpl.subarray
  File "tiledb/libtiledb.pyx", line 3773, in tiledb.libtiledb.DenseArrayImpl._read_dense_subarray
  File "tiledb/libtiledb.pyx", line 3512, in tiledb.libtiledb.ReadQuery.__init__
  File "tiledb/libtiledb.pyx", line 3483, in tiledb.libtiledb.ReadQuery.__init__
  File "tiledb/libtiledb.pyx", line 387, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 372, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::REST] Error: Error in libcurl POST operation: libcurl error message 'CURLE_OK'; HTTP code 400; 
```

Code:
```
import tiledb
import tiledb.cloud


_token="a secret"


def fetch(uri):
    config = tiledb.Config()
    config["rest.token"] = _token
    with tiledb.DenseArray(uri, ctx=tiledb.Ctx(config)) as A:
        print(A.shape, A.nattr, [a.name for a in A.schema])
        print(A[1])


if __name__ == '__main__':
    # works
    fetch("tiledb://TileDB-Inc/quickstart_dense")
    # fails
    fetch("tiledb://CZI_Dev/pbmc33k_processed-Xr3zstd_X")
```

**Comment by Shelnutt2** [comment]
@bkmartinjr Is this array in us-east-2 region? It looks like we detected it as us-east-1 when you first registered the array, but we are failing to access it because the proper region is us-east-2.

If the array is indeed in us-east-2 can you please deregister and re-register the array to see if we correctly detect the region? You should be able to remove the array from the settings page on the UI, https://console.tiledb.com/arrays/details/CZI_Dev/pbmc33k_processed-Xr3zstd_X/settings. Or with the tiledb-cloud-py package you can use `tiledb.cloud.deregister_array("tiledb://CZI_Dev/pbmc33k_processed-Xr3zstd_X")`.

**Comment by bkmartinjr** [comment]
Hi Seth - you are right - I goofed and put the bucket in the wrong region.  But overhead/cost aside, it should still work, right?

I dropped the array and re-added it, using the console, and with the same name.   It seems to fail in the same manner as before (same exception).

**Comment by Shelnutt2** [comment]
@bkmartinjr thank you for testing the registration again. You are correct in that any region bucket should work with the service. When an array is registered we use the AWS SDK to check the bucket region and store than for subsequent access of the array.

We are investing this now and will let you know when we have an update.

As a general note, TileDB Cloud is currently only hosted in `us-east-1` so any other region will incur cross-region access cost and performance penalties as you mention, but should work.

**Comment by bkmartinjr** [comment]
Hi @Shelnutt2 - I have moved everything to us-east-1, and I can confirm that it now works OK.

**Comment by Shelnutt2** [comment]
@bkmartinjr the fix for this has been deployed, your array in us-east-2 should work now.
