### ISSUE TITLE
Building wheel for tiledb (setup.py) ... error

### ISSUE THREAD

**Issue by Donaldpherman** [TileDB-Inc/TileDB-Py#300]
I'm having trouble building and install tiledb using pip.  Any help is appreciated.  
Here is trace make:

```
Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pip install tiledb
Collecting tiledb
  Using cached tiledb-0.5.9.tar.gz (100 kB)
Requirement already satisfied: numpy>=1.7 in c:\python38\lib\site-packages (from tiledb) (1.18.2)
Requirement already satisfied: wheel>=0.30 in c:\python38\lib\site-packages (from tiledb) (0.34.2)
Building wheels for collected packages: tiledb
  Building wheel for tiledb (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\donal\AppData\Local\Temp\pip-wheel-z_havapm'
       cwd: C:\Users\donal\AppData\Local\Temp\pip-install-4jujruod\tiledb\
  Complete output (15 lines):
  libtiledb_exists checking 'library_dirs': []
  libtiledb_exists found: 'None'
  running bdist_wheel
  GNU Make 4.3
  Built for Windows32
  Copyright (C) 1988-2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  error: [WinError 2] The system cannot find the file specified
  libtiledb_exists checking 'library_dirs': []
  libtiledb_exists found: 'None'
  Downloading TileDB package from 1.7.7...
  Building libtiledb in directory C:\Users\donal\AppData\Local\Temp\pip-install-4jujruod\tiledb\build\TileDB-1.7.7\build...
  CMake configure command: ['cmake', '-DCMAKE_INSTALL_PREFIX=C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\build\\TileDB-1.7.7\\dist', '-DTILEDB_TESTS=OFF', '-DTILEDB_S3=ON', '-DTILEDB_HDFS=OFF', '-DTILEDB_INSTALL_LIBDIR=lib', '-DTILEDB_CPP_API=OFF', '-DTILEDB_LOG_OUTPUT_ON_FAILURE=ON', '-DTILEDB_FORCE_ALL_DEPS:BOOL=OFF', '-DTILEDB_SERIALIZATION:BOOL=OFF', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64', '-DMSVC_MP_FLAG=/MP4', 'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\build\\TileDB-1.7.7']
  ----------------------------------------
  ERROR: Failed building wheel for tiledb
  Running setup.py clean for tiledb
Failed to build tiledb
Installing collected packages: tiledb
    Running setup.py install for tiledb ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\donal\AppData\Local\Temp\pip-record-3k5yvdtk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\tiledb'
         cwd: C:\Users\donal\AppData\Local\Temp\pip-install-4jujruod\tiledb\
    Complete output (37 lines):
    libtiledb_exists checking 'library_dirs': []
    libtiledb_exists found: 'None'
    running install
    running build
    running build_py
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\tiledb
    copying tiledb\array.py -> build\lib.win-amd64-3.8\tiledb
    copying tiledb\highlevel.py -> build\lib.win-amd64-3.8\tiledb
    copying tiledb\metadata.py -> build\lib.win-amd64-3.8\tiledb
    copying tiledb\multirange_indexing.py -> build\lib.win-amd64-3.8\tiledb
    copying tiledb\version.py -> build\lib.win-amd64-3.8\tiledb
    copying tiledb\__init__.py -> build\lib.win-amd64-3.8\tiledb
    creating build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\all.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\common.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_dask.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_domain_index.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_examples.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_libtiledb.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_metadata.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_multi_index.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_pandas_dataframe.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\test_util.py -> build\lib.win-amd64-3.8\tiledb\tests
    copying tiledb\tests\__init__.py -> build\lib.win-amd64-3.8\tiledb\tests
    running build_ext
    GNU Make 4.3
    Built for Windows32
    Copyright (C) 1988-2020 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    error: [WinError 2] The system cannot find the file specified
    libtiledb_exists checking 'library_dirs': []
    libtiledb_exists found: 'None'
    Building libtiledb in directory C:\Users\donal\AppData\Local\Temp\pip-install-4jujruod\tiledb\build\TileDB-1.7.7\build...
    CMake configure command: ['cmake', '-DCMAKE_INSTALL_PREFIX=C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\build\\TileDB-1.7.7\\dist', '-DTILEDB_TESTS=OFF', '-DTILEDB_S3=ON', '-DTILEDB_HDFS=OFF', '-DTILEDB_INSTALL_LIBDIR=lib', '-DTILEDB_CPP_API=OFF', '-DTILEDB_LOG_OUTPUT_ON_FAILURE=ON', '-DTILEDB_FORCE_ALL_DEPS:BOOL=OFF', '-DTILEDB_SERIALIZATION:BOOL=OFF', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64', '-DMSVC_MP_FLAG=/MP4', 'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\build\\TileDB-1.7.7']
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-4jujruod\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\donal\AppData\Local\Temp\pip-record-3k5yvdtk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\tiledb' Check the logs for full command output.
```

**Comment by ihnorton** [comment]
@Donaldpherman currently we have binary packages for Windows on [conda](https://conda.io/en/latest/), installable with ‘conda install -c conda-forge tiledb-py’.

Installing through pip on Windows requires to be run via a visual studio command prompt with CMake available (vs2015+), which will build all dependencies from source.

(If the above steps aren’t feasible, I can look in to building windows wheels for python 3.7 and 3.8)

**Comment by Donaldpherman** [comment]
@ihnorton thanks for the help.  I can't get it to work with vs2017 but I'll try condo next.

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.21
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>pip install tiledb
Collecting tiledb
  Using cached tiledb-0.5.9.tar.gz (100 kB)
Requirement already satisfied: numpy>=1.7 in c:\python38\lib\site-packages (from tiledb) (1.18.2)
Requirement already satisfied: wheel>=0.30 in c:\python38\lib\site-packages (from tiledb) (0.34.2)
Building wheels for collected packages: tiledb
  Building wheel for tiledb (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\donal\AppData\Local\Temp\pip-wheel-llnr5v72'
       cwd: C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb\
  Complete output (29 lines):
  libtiledb_exists checking 'library_dirs': []
  libtiledb_exists found: 'None'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb\setup.py", line 572, in <module>
      setup(
    File "c:\python38\lib\site-packages\setuptools\__init__.py", line 143, in setup
      _install_setup_requires(attrs)
    File "c:\python38\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "c:\python38\lib\site-packages\setuptools\dist.py", line 695, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
      dist = best[req.key] = env.best_match(
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
      return self.obtain(req, installer)
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
      return installer(requirement)
    File "c:\python38\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "c:\python38\lib\site-packages\setuptools\installer.py", line 133, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 103, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 111, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 132, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\.eggs\\Cython-0.29.16-py3.8-win32.egg'
  ----------------------------------------
  ERROR: Failed building wheel for tiledb
  Running setup.py clean for tiledb
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb
  Complete output (29 lines):
  libtiledb_exists checking 'library_dirs': []
  libtiledb_exists found: 'None'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb\setup.py", line 572, in <module>
      setup(
    File "c:\python38\lib\site-packages\setuptools\__init__.py", line 143, in setup
      _install_setup_requires(attrs)
    File "c:\python38\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "c:\python38\lib\site-packages\setuptools\dist.py", line 695, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
      dist = best[req.key] = env.best_match(
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
      return self.obtain(req, installer)
    File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
      return installer(requirement)
    File "c:\python38\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "c:\python38\lib\site-packages\setuptools\installer.py", line 133, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 103, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 111, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "c:\python38\lib\site-packages\setuptools\wheel.py", line 132, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\.eggs\\Cython-0.29.16-py3.8-win32.egg'
  ----------------------------------------
  ERROR: Failed cleaning build dir for tiledb
Failed to build tiledb
Installing collected packages: tiledb
    Running setup.py install for tiledb ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\donal\AppData\Local\Temp\pip-record-qiyyhhb_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\tiledb'
         cwd: C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb\
    Complete output (29 lines):
    libtiledb_exists checking 'library_dirs': []
    libtiledb_exists found: 'None'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\donal\AppData\Local\Temp\pip-install-vg7g3h6_\tiledb\setup.py", line 572, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\python38\lib\site-packages\setuptools\installer.py", line 133, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "c:\python38\lib\site-packages\setuptools\wheel.py", line 103, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "c:\python38\lib\site-packages\setuptools\wheel.py", line 111, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "c:\python38\lib\site-packages\setuptools\wheel.py", line 132, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\.eggs\\Cython-0.29.16-py3.8-win32.egg'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"'; __file__='"'"'C:\\Users\\donal\\AppData\\Local\\Temp\\pip-install-vg7g3h6_\\tiledb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\donal\AppData\Local\Temp\pip-record-qiyyhhb_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\tiledb' Check the logs for full command output.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>

**Comment by ihnorton** [comment]
@Donaldpherman I've just uploaded wheels for TileDB-Py 0.5.9 to PyPI: https://pypi.org/project/tiledb/0.5.9/#files

At this point we can only support 3.7 and 3.8 wheels due to ABI reasons (it may be possible to do 3.6 as well but I have not tested yet).

I have successfully run our test suite against these wheels, but have not otherwise used/tested the wheels -- so please do let me know if there are any issues. Hope this helps get going.

**Comment by Donaldpherman** [comment]
thanks, it now installs fine for me.
