### ISSUE TITLE
Python tutorial for sparse arrays outdated

### ISSUE THREAD

**Issue by michael-imbeault** [TileDB-Inc/TileDB-Py#340]
From https://docs.tiledb.com/main/quickstart, the Python sections:

`def read_array():
    # Open the array and read from it.
    with tiledb.SparseArray(array_name, mode='r') as A:
        # Slice only rows 1, 2 and cols 2, 3, 4.
        data = A[1:3, 2:5]
        a_vals = data["a"]
        for i, coord in enumerate(data["coords"]):
            print("Cell (%d, %d) has data %d" % (coord[0], coord[1], a_vals[i]))
`

data['coords'] doesn't exist - instead data contains 'dim1' and 'dim2' - could the tutorial be updated?

**Comment by ihnorton** [comment]
Hi @michael-imbeault, updated - thank you! The change was as follows:
```
for i, coord in enumerate(data["coords"]):
```
to
```
for i, coord in enumerate(zip(data['d1'], data['d2'])):
```

The reason is that each dimensions coordinates are now stored/returned separately, which facilitates one of the new features in TileDB 2.0: the capability to store sparse arrays with mixed dimension types.
