### ISSUE TITLE
Conditional queries and supporting indexes (Question)

### ISSUE THREAD

**Issue by bimtauer** [TileDB-Inc/TileDB-Py#358]
Hi, I'm currently assessing whether tiledb would be a promising solution for a point cloud project I am working on. 

Fast spatial indexing is already a great benefit, but I need to know whether it is possible to index the data on other attributes as well and whether conditional queries on these attributes are possible/will be possible at some point. 

A typical use case would for example involve the "ReturnNumber" integer attribute of a point cloud and querying all points within a certain area for which ReturnNumber = 0. I'm aware that I can do that with tiledb after having used spatial indexing, but point clouds can be very large and I would like to avoid loading the entire area first. 

Would it be possible in this case to create an index for the "ReturnNumber" attribute and use it for queries instead of or in addition to the spatial index?

Thanks a lot, I would greatly appreciate a short answer!

**Comment by stavrospapadopoulos** [comment]
Hi Tim, you are right, currently the attribute filtering is done outside TileDB and after you slice, e.g., it could be done with numpy or Pandas. Ideally, you would like to push the filter condition to the TileDB core storage engine and get directly only the results. This filter push down is among the top features in our roadmap. Please stay tuned.

**Comment by bimtauer** [comment]
Thanks for the answer and great to hear that it's on the roadmap. Having that feature would make tiledb pretty much unbeatable for our purposes! 
Is something similar already possible with another API, C++ for example?

**Comment by stavrospapadopoulos** [comment]
When you slice data with TileDB-Py, the result is a dictionary of numpy arrays. You can filter directly with numpy then on the attribute buffer. 

@ihnorton @normanb  could you please provide a quick example? We can then enhance the example and post a more detailed Jupyter notebook shortly after.

**Comment by normanb** [comment]
@bimtauer I have created a TileDB array from a sample LAZ file from the NEON [portal](https://www.neonscience.org/) using [PDAL](https://pdal.io/);

`pdal pipeline -i pipeline.json`

Where the pipeline consists of 

```json
[
        "unclassified_point_cloud.laz",
        {
                "type": "filters.chipper",
                "capacity": "10000000"
        },
        {
                "type": "writers.tiledb",
                "array_name": "output_pc",
                "chunk_size":  10000000
        }
]
```

And the example TileDB-Py code to query a subset of this array using native coordinates and filter on a attribute is below;

```python
import time

import tiledb


def sample_query(array_name):
    x1, x2, y1, y2, z1, z2 = 544230,545300,4977811,4979913,1226,3050
    config = tiledb.Config()
    config['sm.num_reader_threads'] = 8
    config['vfs.num_threads'] = 8
    config['py.init_buffer_bytes'] =  1000000000

    with tiledb.open(array_name, config=config) as arr:
        print('query bbox: {}'.format([x1, x2, y1, y2, z1, z2]))

        dom = arr.nonempty_domain()
        print('Non-empty domain: {}'.format(dom))

        st = time.time()
        results = arr.multi_index[x1:x2, y1:y2, z1:z2]
        print("query completed in {} seconds".format(time.time() - st))

        xs = results['X']
        print(f"Points returned: {len(xs)}")

        # filter on return number
        msk = results['ReturnNumber'] == 1

        print(f"Filtered {len(xs[msk])} points")



if __name__ == "__main__":
    array_name = 'output_pc'
    sample_query(array_name)
```

As @stavrospapadopoulos mentioned we are looking to push the filter condition down to TileDB and this is on our roadmap. Let us know if we can help further.

**Comment by bimtauer** [comment]
@normanb @stavrospapadopoulos  Thanks a lot for your efforts! This last example pipeline is very similar to tasks that we are currently dealing with. 
We're actually aiming to replace pdal's chipper (because its very RAM intensive for large clouds) by first creating an index that would reference the bounds of tiles roughly equal in point size and load them selectively through TileDBs spatial indexing. These kinds of functions already work and help us a lot. 

But yes in many cases we also need to load selected points from large clouds, not by location but by a specific, attribute based query. These points could make up only 0.1% or less of the entire point cloud, thus any solution that reads first and filters later, whether tile-based or not, will create unnecessary cost. This is what we really hope to avoid. 

I'll try to follow your roadmap by checking in on your repos regularly, very excited about what's yet to come!

**Comment by bimtauer** [comment]
Actually I just stumbled over this discussion [here](https://github.com/TileDB-Inc/TileDB/issues/675), concerning "support non-continuous subsetting", which led me to one more question:

Is it possible to query point cloud sparse 3D arrays in this manner? Or is any reference to original point order impossible once the data has been reorganized for the spatial index? 

This kind of row/col indexing would also help us a lot - cause usually we know the point ids of the specific points we're interested in.

**Comment by stavrospapadopoulos** [comment]
> Is it possible to query point cloud sparse 3D arrays in this manner? Or is any reference to original point order impossible once the data has been reorganized for the spatial index? The [PR](https://github.com/TileDB-Inc/TileDB/pull/1305) only implemented this for Dense Arrays right?

Non-contiguous subsetting currently works for both dense and sparse arrays. Therefore, you can use this for the point cloud 3D arrays without problems.

> So to clarify: If attribute conditioned queries are still in the making, maybe it's the case that queries based on point id are already possible through some workaround? Is that so?

Hmm, not sure if I understand correctly, but the best workaround currently until TileDB supports attribute filtering is to convert that attribute into a dimension. That is, in addition to the three XYZ dimensions, you could add a fourth one (or any number of dimensions really) for the point id or any other attribute, which will effectively enable you to slice fast on that extra attribute as well.

Of course, that does not generalize to a huge number of dimensions: you typically want to keep the number of dimensions low (otherwise the internal multi-D indices like our R-tree will not perform great) and highly selective so that your slicing prunes quickly a lot of irrelevant data to your results. 

Please stay tuned for updates on attribute filtering, as we will be working actively on it in the near future. That will give you tons of flexibility to tune the TileDB performance to your application.

**Comment by bimtauer** [comment]
@stavrospapadopoulos I see, adding a fourth dimension would actually be very helpful and pretty much solve it for us! Thanks a lot.
