### ISSUE TITLE
Add GCS support to Python wheels

### ISSUE THREAD

**Issue by ihnorton** [TileDB-Inc/TileDB-Py#361]
We need to add GCS support to the Python wheels.

---
[ch2680]

**Comment by ihnorton** [comment]
Fixed by https://github.com/TileDB-Inc/TileDB-Py/pull/364.

**Comment by ihnorton** [comment]
@jpdark (and @nbren12), GCS support is available in the latest PyPI wheels for macOS and linux (note: manylinux2010 version only, which should be preferred automatically by `pip`).

Please see [this page](https://docs.tiledb.com/main/backends/gcs) for background, but a quick demo here:

1) export the credential path in your shell:
```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/serviceaccount.json
```
2) run tiledb
```
import tiledb
import numpy as np

v = tiledb.VFS()

print("vfs supports gcs?: ", v.supports("gcs")) # should return True

array_uri = "gcs://your-bucket/your-array-path"

# create a test array
with tiledb.from_numpy(array_uri, np.random.rand(4,4)) as A:
    pass

with tiledb.open(array_uri) as A:
    print("schema: ", A.schema)
    print("data: ", A[:])
```

**Comment by ihnorton** [comment]
Also, please let us know if there are any unexpected issues -- we will be happy to iterate and fix.

**Comment by nbren12** [comment]
Thanks for looking into this! I will give it a try. BTW, how reliable have you found using GCS? We normally use gcsfs+zarr, but have been having some issues with incomplete retry logic in gcsfs causing long running jobs to fail. 

I think that situation is slowly being improved, but I'm just trying to gauge how experimental the GCS support in tiledb is.

**Comment by jpdark** [comment]
Thanks for the heads up and how-to @ihnorton.
I'll make sure to give it a spin this week and report back.

**Comment by ihnorton** [comment]
@nbren12 our core library testing includes a number of generic filesystem-operation tests that are run against each specific backend, as well as a set of GCS-specific tests. We've also benchmarked the GCS backend against our S3 and Azure implementations with datasets in the 10 GB range, and have found all three of them to be comparable in terms of performance. That said, GCS is pretty new to us, so we would be grateful for any bug reports (and will aim to turn them around quickly).

**Comment by nbren12** [comment]
Thanks for letting me know. The issues we have are pretty intermittent, but do appear at the 10 GB range, especially if there are many files. I will let you know if we run into any problems.
