### ISSUE TITLE
Problem with the SSL CA cert

### ISSUE THREAD

**Issue by habibutsu** [TileDB-Inc/TileDB-Py#372]
I am trying to run following code:
```python
import os
import tiledb

print('GOOGLE_APPLICATION_CREDENTIALS', os.environ['GOOGLE_APPLICATION_CREDENTIALS'] )
print('tiledb-py', tiledb.__version__)
print('libtiledb', tiledb.libtiledb.version())
cfg = tiledb.Config()
cfg['vfs.gcs.project_id'] = 'innate-setup-260511'
a = tiledb.Array('gcs://habibutsu-test-bucket/data', mode='w', ctx=tiledb.Ctx(cfg))
```

As result it was gotten following output:

```bash
GOOGLE_APPLICATION_CREDENTIALS /home/habibutsu/.secrets/gcs-storage-key.json
tiledb-py 0.6.5
libtiledb (2, 0, 6)
---------------------------------------------------------------------------
TileDBError                               Traceback (most recent call last)
<ipython-input-18-05241fa1272f> in <module>
      5 cfg = tiledb.Config()
      6 cfg['vfs.gcs.project_id'] = 'innate-setup-260511'
----> 7 a = tiledb.Array('gcs://habibutsu-test-bucket/data', mode='w', ctx=tiledb.Ctx(cfg))

tiledb/libtiledb.pyx in tiledb.libtiledb.Array.__init__()

tiledb/libtiledb.pyx in tiledb.libtiledb.preload_array()

tiledb/libtiledb.pyx in tiledb.libtiledb._raise_ctx_err()

tiledb/libtiledb.pyx in tiledb.libtiledb._raise_tiledb_error()

TileDBError: [TileDB::?] Error:: List objects failed on: gcs://habibutsu-test-bucket/data/ (Permanent error in ListObjects: EasyPerform() - CURL error [77]=Problem with the SSL CA cert (path? access rights?) [UNKNOWN])
```

What is the problem?

**Comment by joe-maley** [comment]
The problem is that the networking library, _curl_, is unable to locate the SSL CA certificate on your machine. What operating system (and associated version) are you using?

**Comment by habibutsu** [comment]
@joe-maley 
```
▶ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
▶ uname -a
Linux habibutsu 5.3.0-62-generic #56-Ubuntu SMP Tue Jun 23 11:20:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Hmm, it is strange because there no config parameter for `gcs` where I can to set certificate and i was supposing that json-file with credentials for service_account is enough

**Comment by ihnorton** [comment]
Hi @habibutsu, I reproduced the issue on ubuntu. I have just merged a fix in the core library which applies TileDB's certificate path detection for GCS as well, and I confirmed the patch will allow using wheels on multiple linux distros. The issue is that the python PyPI wheels are built on CentOS-equivalent ("manylinux2010"), and GCS/curl hard-codes the path to the certificates which were available the build system. 

We will have a new binary release today or monday including the patch. Thanks!

**Comment by habibutsu** [comment]
@ihnorton Thanks, I'll try to use it

**Comment by ihnorton** [comment]
Hi @habibutsu, the fix for this issue is included in the [latest TileDB-Py release](https://pypi.org/project/tiledb/0.6.6/) (0.6.6) on PyPI. Please let us know if the issue is not resolved after upgrading.

**Comment by habibutsu** [comment]
@ihnorton Yes, now it works. Thanks!

**Comment by ihnorton** [comment]
Thank you for confirming!
