### ISSUE TITLE
Clear cell in Sparse/Dense Arrays

### ISSUE THREAD

**Issue by DanielGrigorasch** [TileDB-Inc/TileDB-Py#380]
I create a SparseArray (or DenseArray). Then I put some Strings in it (type ```numpy.dtype("U1")```).  Now I want the cell to be empty again. How do I do that?
If I write ```array[index] = np.array([""]```), then the String is empty but the cell still contains the empty String.
So is it possible to remove it completly from the Array like it was befor writing any data in it?
Is it possible with other datatypes like int, too?

I read the Docs: https://docs.tiledb.com/main/basic-concepts/writing but I did not manage to do ist myself.

Thanks

**Comment by stavrospapadopoulos** [comment]
You are referring to natively supporting cell deletions in TileDB. In our roadmap and tracked here (I just added the feature, although this has been on our radar for a while now): https://feedback.tiledb.com/tiledb-core/p/support-for-deletions
