### ISSUE TITLE
Indexing Arrays

### ISSUE THREAD

**Issue by DanielGrigorasch** [TileDB-Inc/TileDB-Py#385]
Hello,

is it possible to pass a numpy array as an index like it is possible with numpy-arrays?
```
arr = np.array([1, 2, 3, 4])
indices = np.array([0, 2, 3])
print(arr[indices.reshape(1, -1)])
```

Thanks

**Comment by ihnorton** [comment]
Hi @DanielGrigorasch, not currently, but we can now support this by iterating the indexes and setting as point-ranges for a multi-range query (which is what `arr.multi_index[...]` does) -- we will add this for "standard numpy indexing" soon.
