### ISSUE TITLE
quickstart - page not found

### ISSUE THREAD

**Issue by pydatasci-repo** [TileDB-Inc/TileDB-Py#386]
![image](https://user-images.githubusercontent.com/71051965/95029999-53677d00-067a-11eb-9498-40796250b7b0.png)

https://docs.tiledb.com/main/quickstart

**Comment by ihnorton** [comment]
Thanks for pointing this out, I will update the links shortly. Here is the equivalent content:

- https://docs.tiledb.com/main/solutions/tiledb-embedded/installation/quick-install
- https://docs.tiledb.com/main/solutions/tiledb-embedded/usage/python
