### ISSUE TITLE
Clean up during/handle KeyboardInterrupts

### ISSUE THREAD

**Issue by tdenniston** [TileDB-Inc/TileDB-Py#39]
With the upcoming ability to cancel TileDB queries, a `^C` will result in cancelling the queries, but losing the error message. We should do something like wrap all query submit calls in a try/catch, e.g.:
```

        rc = TILEDB_OK
        try:
            with nogil:
                rc = tiledb_query_submit(ctx_ptr, query_ptr)
        except KeyboardInterrupt:
            check_error(ctx, rc)
        finally:
            PyMem_Free(attr_names_ptr)
            PyMem_Free(buffers_ptr)
            PyMem_Free(buffer_sizes_ptr)
            tiledb_query_free(ctx_ptr, &query_ptr)

```

**Comment by jakebolewski** [comment]
@ihnorton I believe that this can be closed?

**Comment by ihnorton** [comment]
It looks like there are several calls `..query_submit` calls that are not wrapped in a try block. Is this no longer necessary / handled in core?
