### ISSUE TITLE
core.cc, PyQuery py::class_<PyQuery>(m, "PyQuery") .def incorrect?

### ISSUE THREAD

**Issue by d-hoke** [TileDB-Inc/TileDB-Py#399]
seen at commit 50b53eb, core.cc, line 862 (core.cc Latest commit a2c35e9)
      .def("import_buffer", &PyQuery::unpack_buffer)`

code implemented possibly at:
https://github.com/TileDB-Inc/TileDB-Py/commit/fef69325e060b8dacf7d5ac3e3d70a342b0f0141

Is that supposed to be:
`      .def("import_buffer", &PyQuery::import_buffer)`

more context, current:
      .def("unpack_buffer", &PyQuery::unpack_buffer)
      .def("import_buffer", &PyQuery::unpack_buffer)
      .def("_test_array", &PyQuery::_test_array)

suspected should be:
      .def("unpack_buffer", &PyQuery::unpack_buffer)
      .def("import_buffer", &PyQuery::import_buffer)
      .def("_test_array", &PyQuery::_test_array)

**Comment by ihnorton** [comment]
Thank you for pointing this out: the pybind definition for `def("import_buffer", &PyQuery::unpack_buffer)` was unintentional, I will remove (#400).
