### ISSUE TITLE
How to get all the non-empty coordinates from sparse array?

### ISSUE THREAD

**Issue by WarBean** [TileDB-Inc/TileDB-Py#441]
Suppose I create a sparse array:

```
import tiledb
import numpy as np


path = 'test.tiledb'
dim1 = tiledb.Dim(name='dim1', domain=(None, None), tile=None, dtype=np.bytes_)
dim2 = tiledb.Dim(name='dim2', domain=(None, None), tile=None, dtype=np.bytes_)
attr = tiledb.Attr(name='attr', dtype=np.float32)
dom = tiledb.Domain(dim1, dim2)
schema = tiledb.ArraySchema(domain=dom, sparse=True, attrs=[attr])
tiledb.Array.create(path, schema)

with tiledb.open(path, 'w') as array:
    array['a1', 'b1'] = 1
    array['a1', 'b2'] = 2
    array['a2', 'b1'] = 3
    array['a3', 'b1'] = 4
```

How can I retrieve all the "keys" from `array`, like `array.dim('dim1').values()` or `array.coordinates('dim1')`, which should return `['a1', 'a2', 'a3']`?

**Comment by ihnorton** [comment]
Hi @WarBean,

Two other quick comments:

- If you want only the start/end values of a dimension coordinate range, you can look this up with the `a.nonempty_domain()` function. That function will return a tuple of (start, end) pairs, one per dimension (this is what TileDB documentation means referring to “nonempty domain”).

- We would be interested to hear more about your use-case and goals. TileDB sparse arrays can work very well as a key-value store like this, especially for very large datasets, and we are continuously optimizing as new use-cases come up.

**Comment by WarBean** [comment]
Thanks for your response! @ihnorton 

Here is my real use case: I'm doing some deep learning project, with a text file recording my training samples:

```
{"filename": "sample1.jpg", "label": [["tag1", 1], ["tag3", 0], ["tag7", 0.5]]}
{"filename": "sample2.jpg", "label": [["tag2", 1]]}
{"filename": "sample3.jpg", "label": [["tag5", 0.3], ["tag8", 0.4]]}
......
```

Then I found it cumbersome to query "all filenames that belong to some specific label". So I plan to reformulate this file into some kind of sparse matrix, with `filename` as one matrix dimension and `label` as another:

```
matrix["sample1.jpg", "tag1"] => 1
matrix["sample1.jpg", "tag7"] => 0.5
matrix["sample1.jpg"] => all labels and corresponding scores associated with "sample1.jpg"
matrix["tag3"] => all filenames and corresponding scores associated with "tag3"
```

TileDB supports all these operations so far. However, I also want to retrieve all the existing filenames or labels. In this case, `nonempty_domain` only returns the left-most and right-most keys. `.query(attrs=[])` returns all the keys, but not as a unique set. Since one filename is often associated with multiple labels and one label is often associated with multiple filenames, the returned keys from `.query(attrs=[])` will be much longer than needed.

It would be better TileDB implements a new API to return unique keys of some specific dimension.

**Comment by ihnorton** [comment]
Hi @WarBean, ok, thanks for explaining the situation.

> TileDB implements a new API to return unique keys of some specific dimension.

I am adding this feature request to our list and will implement soon. (in the meantime, one option is to call `np.unique` on the result array)

**Comment by nguyenv** [comment]
Hi @WarBean.

We have now implemented `.unique_dim_values()` that functions as you requested. Example usage and output can be viewed [here](https://github.com/TileDB-Inc/TileDB-Py/blob/6bbbf8757a98ba6b23c64bb2279df2ba99a619ba/tiledb/tests/test_libtiledb.py#L2188-L2210). Let us know if you any further questions.

**Comment by WarBean** [comment]
@nguyenv That is what I need, nice work!
