### ISSUE TITLE
GCS storage - can create, but can't read

### ISSUE THREAD

**Issue by lunaroverlord** [TileDB-Inc/TileDB-Py#443]
Hi there, I'm unable to get TileDB (Python) to read from GCS. It creates the objects, but fails to read them.

#### Versions
TileDB 0.7.3
Python 3.7.5

### Create an empty schema
Using service account credentials with read & write access (`GOOGLE_APPLICATION_CREDENTIALS`)
```
import numpy as np
import tiledb

dim_channel = tiledb.Dim(name="channel", domain=(0, 3), tile=1, dtype=np.int32)
domain = tiledb.Domain(dim_channel)
filters = tiledb.FilterList([tiledb.ZstdFilter(level=10)])
attrs = [tiledb.Attr(dtype=np.float32, filters=filters)]
schema = tiledb.ArraySchema(domain=domain, sparse=False, attrs=attrs)
tiledb.DenseArray.create("gcs://tiledb/test", schema)
```
Objects are created in the bucket.

### Try to open it
Using same credentials as above
```
with tiledb.open("gcs://tiledb/test", "r") as tdb:
    print(tdb)
```
gives 
```
TileDBError: [TileDB::?] Error:: Read object failed on: gcs://tiledb/test/__array_schema.tdb
```
Similarly, `tiledb.array_exists("gcs://tiledb/test")` returns False

Full traceback:
```
tiledb/libtiledb.pyx(5926)tiledb.libtiledb.VFS.read()
tiledb/libtiledb.pyx(5907)tiledb.libtiledb.VFS.readinto()
tiledb/libtiledb.pyx(479)tiledb.libtiledb._raise_ctx_err()
tiledb/libtiledb.pyx(464)tiledb.libtiledb._raise_tiledb_error()
```
### __array_schema.tdb can be accessed
This outputs the contents of __array_schema.tdb, so it can't be a permissions issue.
```
from google.cloud import storage
client = storage.Client()
bucket = client.get_bucket('tiledb')
blob = bucket.get_blob('test/__array_schema.tdb')
print(blob.download_as_string())
```
Is it a bug or am I doing something wrong?

**Comment by ihnorton** [comment]
Hi @lunaroverlord, thank you for opening the issue. I confirmed the problem and we are investigating, will get back to you as soon as possible.

**Comment by ihnorton** [comment]
Hi @lunaroverlord, we have a fix pending in https://github.com/TileDB-Inc/TileDB/pull/1966 which will be available in a release version soon. In the meantime, here is a work-around, thanks to @joe-maley:


```
# run these lines before any other TileDB commands
import tiledb
cfg = {'vfs.read_ahead_size': 0}
tiledb.default_ctx(cfg)

# now continue as above
# ...

with tiledb.open("gcs://tiledb/test", "r") as tdb:
    print(tdb)
```

**Comment by lunaroverlord** [comment]
Thank you @ihnorton and @joe-maley , the workaround works and our issue is solved.
