### ISSUE TITLE
Sparse writing in Dense Arrays is not working as documented.

### ISSUE THREAD

**Issue by jorgeecardona** [TileDB-Inc/TileDB-Py#445]
The feature described in https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/writing-arrays/writing-sparse-cells does not work for Dense Arrays, only for SparseArrays. It raises the following error:

```python
...
    A[m.row, m.col] = m.data
  File "tiledb/libtiledb.pyx", line 4829, in tiledb.libtiledb.DenseArrayImpl.__setitem__
  File "tiledb/libtiledb.pyx", line 3129, in tiledb.libtiledb.index_domain_subarray
IndexError: invalid index type: <class 'numpy.ndarray'>
```
 I just compiled the dev of TileDB and TileDB-Py under conda with python 3.8.5 on a Debian sid.

**Comment by ihnorton** [comment]
Hi @jorgeecardona, thanks for opening this issue and apologies for the delayed fix. This issue has been fixed in the latest release, 0.8.6, available on PyPI and via conda.
