### ISSUE TITLE
Four components should be three components?

### ISSUE THREAD

**Issue by donno** [TileDB-Inc/TileDB-Py#500]
In the recently created example "writing_dense_rgb.py" there is this fragment:
https://github.com/TileDB-Inc/TileDB-Py/blob/75ddcf56ed80ba5e1a1237b7e527ec4fbd87abb9/examples/writing_dense_rgb.py#L56-L57

It says four int32 components where it seems like it should be three int32 components. After all the values of the attribute are RGB and not RGBA.

**Comment by ihnorton** [comment]
Thanks for catching that! Fix in #501
