### ISSUE TITLE
FragmentInfoList doesn't pass ctx

### ISSUE THREAD

**Issue by gatesn** [TileDB-Inc/TileDB-Py#577]
I think the ctx needs to be passed here:

https://github.com/TileDB-Inc/TileDB-Py/blob/a529b1617190c17c3ae458dcf10a8b0de08ea281/tiledb/fragment.py#L17-L18

**Comment by ihnorton** [comment]
cc @nguyenv

**Comment by ihnorton** [comment]
Fixed by https://github.com/TileDB-Inc/TileDB-Py/pull/578
