### ISSUE TITLE
How to append data to variable size attribute

### ISSUE THREAD

**Issue by digital-idiot** [TileDB-Inc/TileDB-Py#643]
I intend to create a `2D` sparse array  with a single attribute `a`. Each cell of the attribute `a` will be holding a `float32` vector of variable length. I create the array using following function:

```python
import numpy as np
import tiledb

def create_array(array_name):
    dom = tiledb.Domain(
        tiledb.Dim(name="rows", domain=(1, 1000), tile=4, dtype=np.int64),
        tiledb.Dim(name="cols", domain=(1, 1200), tile=4, dtype=np.int64)
    )
    schema = tiledb.ArraySchema(
        domain=dom, sparse=True,
        attrs=[
            tiledb.Attr(name="a", var=True, dtype=np.float32),
        ]
    )
    tiledb.SparseArray.create(array_name, schema)
```
For writing I use the following function:

```python
def write_array(array_name, ix, jx, dat):
    with tiledb.SparseArray(array_name, mode="w") as fp:
        fp[ix, jx] = dat
```
For example, the following works:
```python
i, j = [1, 2, 2], [1, 4, 3]
data = [
    np.arange(5, dtype=np.float32),
    np.arange(12, dtype=np.float32),
    np.arange(3, dtype=np.float32)
]
data = np.array(data, dtype=object)
create_array('foo')
write_array('foo', i, j, data)
```
If I run the following snippet subsequently, the corresponding cells will be overwritten:
```python
m, n = [1, 7, 2], [1, 9, 3]
data1 = [
    np.arange(7, dtype=np.float32),
    np.arange(4, dtype=np.float32),
    np.arange(11, dtype=np.float32)
]
data1 = np.array(data1, dtype=object)
write_array('foo', m, n, data1)
```
In this case cell `(1, 1)` and cell `(2, 3)` will be overwritten with their new values along with a new cell at `(7, 9)`. Instead of overwriting, I want to append the values if there are existing values to a cell, i. e. concatenate the newly given array with the existing array of that cell if exists any. This is because I intend to fill the array iteratively. Is there any way to do it?

**Comment by ihnorton** [comment]
Hi @digital-idiot, thanks for trying TileDB and opening this issue. By default, TileDB overwrites cells with new coordinates. To achieve the behavior you are seeking, you can use `allows_duplicates=True` in the `ArraySchema` construction:

```
schema = tiledb.ArraySchema(
        domain=dom, sparse=True,
        attrs=[
            tiledb.Attr(name="a", var=True, dtype=np.float32),
        ],
        allows_duplicates=True
    )
```

After changing that setting, then following the second write, the coordinates you get back should be:

```
('rows', array([1, 2, 2, 1, 2, 7])), ('cols', array([1, 3, 4, 1, 3, 9]))
```

Along with matching contents for each cell as-written. Hope that helps.

**Comment by ihnorton** [comment]
(by the way: thanks for including reproducible code with a very clear explanation!)

**Comment by digital-idiot** [comment]
> To achieve the behavior you are seeking, you can use allows_duplicates=True in the ArraySchema construction

I see. It does not exactly append to the existing array of that but rather add the current array as another duplicate entry to the corresponding cell. This is referred as `multiplicity`  in the [TileDB data model](https://docs.tiledb.com/main/basic-concepts/data-model).

Although I expected to actually concatenate the array but I suppose I can do that when reading all the entries from a cell and concatenate them at that time. Only question remains is whether order (of insertion) of these duplicate entries will be preserved or not?

Thank you for your prompt response @ihnorton

**Comment by stavrospapadopoulos** [comment]
Hi @digital-idiot, I understand what you are trying to do. This has come up in the past. We'll try to brainstorm on how to handle this. It is rather easy to do so internally, but there is a bit of complexity in user configuration and/or APIs that need to be exposed (e.g., will this be applicable to all cells similar to multiplicities, or only to specific ones - the latter may need some format changes). We'll add this to our roadmap.

**Comment by digital-idiot** [comment]
Thank you for your kind response @ihnorton, much appreciated. I will be glad to see this implemented in near future.
