### ISSUE TITLE
Global context lost between different cells in Jupyter notebook

### ISSUE THREAD

**Issue by mx781** [TileDB-Inc/TileDB-Py#644]
Consider this code, run in a Jupyter notebook setting:

```python
import tiledb
import numpy as np

def make_context():
    tiledb.default_ctx({
        "vfs.s3.aws_access_key_id": "foo",
        "vfs.s3.aws_secret_access_key": "bar"
        # ...etc
    })

def write_array():
    db_id = "test_123"
    resource_id = f"s3://my-bucket/data/{db_id}"
    dims = [
        tiledb.Dim(name="Time",
                   domain=(np.datetime64("1970-01-01"), np.datetime64("2100-01-01")),
                   tile=np.timedelta64(1536, "m"),
                   dtype=np.datetime64('', "m").dtype)
    ]
    domain = tiledb.Domain(*dims)
    filters = tiledb.FilterList([tiledb.ZstdFilter(level=18)])
    attrs = [tiledb.Attr(name="measurement", dtype=np.float32, filters=filters)]
    schema = tiledb.ArraySchema(domain=domain, sparse=False, attrs=attrs)
    return tiledb.DenseArray.create(resource_id, schema)
```

In my workflow it is convenient to run each function in its own cell: I initialise context at the very beginning, then run write operations on the go - I imagine this is pretty common. 

However as of TileDB-Py 0.9.0, the global context seems to be lost, i.e when running separately like so:
```python
# cell 1:
make_context()
# cell 2
write_array()
```

The AWS credentials I set in the context are not present, so it fails with errors like `Error message:  The AWS Access Key Id you provided does not exist in our records.` (as it defaults to an empty key).

If I place both commands in the same cell like so:
```python
# cell 1
make_context()
write_array()
```
it creates the array fine.

I tried downgrading to TileDB-Py 0.8 and the error was no longer present, so this seems like a regression between versions. 

I'm using S3 storage on Wasabi, running Python 3.9 on Ubuntu 20.04. I tried TileDB-Py versions `0.9.0` and `0.9.4` and both seem to fail.

**Comment by ihnorton** [comment]
@mx781 thanks for opening the issue. Could you please share your ipykernel version? I believe this should be fixed in ipykernel 6.0+.

**Comment by mx781** [comment]
@ihnorton thanks for the speedy reply! Right you are - I was on `ipykernel==5.4.3`. Upgrading to latest fixed the issue.

**Comment by ihnorton** [comment]
That's great, thanks for confirming.
