### ISSUE TITLE
Deadlock writing concurrently to S3 array

### ISSUE THREAD

**Issue by gatesn** [TileDB-Inc/TileDB-Py#654]
It seems that TileDB deadlocks when writing concurrently to an array in S3. It doesn't lock up with ThreadPoolExecutor, or when writing to a file:// array.

TileDB-Py 0.9.3
TileDB 2.3.2

```python
from concurrent.futures.process import ProcessPoolExecutor

import numpy as np
from tiledb import *

array_name = 's3://...'
ctx = Ctx(...)

s = ArraySchema(domain=Domain(Dim('a', dtype=np.int8, domain=(0, 126))), attrs=[Attr('x', dtype=np.int32)], sparse=True)

SparseArray.create(array_name, schema=s, ctx=ctx)


def write(i):
    with SparseArray(array_name, mode='w', ctx=ctx) as A:
        A[i] = i  # Processes hang here


with ProcessPoolExecutor() as pool:
    for i in range(50):
        pool.submit(write, i)


with SparseArray(array_name, ctx=ctx) as A:
    print(A[:])
```

**Comment by gatesn** [comment]
The use-case is to back-fill / bulk load data into an array from its current location and format in S3.

Interesting that the thread pool is tied to the context, makes a lot of sense. Is anything else tied to the context that might be worth noting? e.g. the tile cache? 

And does this mean I should be manually "closing" contexts when I no longer need them / want to eagerly get rid of them?

**Comment by ihnorton** [comment]
> Interesting that the thread pool is tied to the context, makes a lot of sense. Is anything else tied to the context that might be worth noting? e.g. the tile cache?

Yes: tile cache, configuration (for backends, such as authentication params), last-error state, and statistics (although this will be per-query in the near future).

> And does this mean I should be manually "closing" contexts when I no longer need them / want to eagerly get rid of them?

A couple notes:
- the tile cache can be helpful for some query patterns
- spinning up thread pools is entirely free, though it is a tiny cost relative to most other operations. more importantly: some systems have limits on total number of threads per process, so you need to make sure the contexts are indeed disposed if you are creating them on-demand (context will not be garbage collected if any references exist)
- for convenience, there are several ways to manage contexts, which can avoid passing a context explicitly to each call:
  - `tiledb.scope_ctx`: a (Python) context manager allowing use of a specific `tiledb.Ctx` object automatically for all `tiledb.` calls in a `with` block. see example usage in this test: https://github.com/TileDB-Inc/TileDB-Py/blob/bda1d5e2d1cafe7c5d8aa8196fdc78f7bdbb39e1/tiledb/tests/test_libtiledb.py#L3851-L3876
  - `tiledb.default_ctx`: this is a single-initialization global context used when no explicit `ctx=` or `with tiledb.scope_ctx` exists. Settings may be configued by running `tiledb.default_ctx(config)` before any other tiledb calls)

**Comment by gatesn** [comment]
This is really helpful thank you. I think I'm doing a few things incorrectly in that case.

One example is I'm constructing some pre-configured FilterLists at the module-level. But this seems to instantiate a context, along with a thread pool. What's the reason a FilterList is tied to a context? And can anything bad happen if I subsequently try to construct an ArraySchema with a different Ctx to the one referenced by the FilterLists?

---

> spinning up thread pools is not entirely free, though it is a tiny cost relative to most other operations... need to make sure the contexts are indeed disposed if you are creating them on-demand (context will not be garbage collected if any references exist)

I don't mind the spin up cost of a thread pool, I'm more concerned about having lots of thread pools lying around unused. It sounds like you're suggesting the thread pools are shut down only when the context is garbage collected? Is it therefore best to call `del my_ctx` to force the __dealloc__ to be called? Does that even force it? Or does Python wait for a gc, which I guess may never happen?

---

The scope_ctx call should be really useful! Particularly for running things like consolidation / vacuuming where the configs describe which mode of consolidation to run.

**Comment by ihnorton** [comment]
> What's the reason a FilterList is tied to a context?

Error-handling in the C API; errors during allocation or in any filterlist specific functions are stored in the context and retrievable from the context after error (pattern is used throughout the C API).

> And can anything bad happen if I subsequently try to construct an ArraySchema with a different Ctx to the one referenced by the FilterLists?

I don't think so, because the context is not even referenced internally. However, cc to @Shelnutt2 and @stavrospapadopoulos in case they have any further comment/clarification.

> Is it therefore best to call del my_ctx to force the dealloc to be called? Does that even force it? Or does Python wait for a gc, which I guess may never happen?

Python's refcount is reliable _unless_ there are cycles, which are easy to create and are only broken by the GC non-deterministically (or by explicit `gc.collect` invocation - which isn't really recommended for routine use). That said, if you are using a fork/spawn-join pattern to distribute work (as above), then each context+threadpool will be cleaned up when the worker process exits.

I would not really recommend creating "lots" of contexts in a single-process situation, the threadpool should handle work splitting there.

**Comment by gatesn** [comment]
All makes sense, thank you.

I think it might be nice if an error was thrown or the AWS SDK was reconstructed if the pid changes, rather than a deadlock. But this issue captures a lot of the context I was missing so also happy to close out.

**Comment by ihnorton** [comment]
I'm hoping we can deal with this using a `pthread_atfork` handler, but may take some time to implement. Will leave this open for now.

**Comment by ihnorton** [comment]
We are doing some rework to improve threading and utilization, and I have a core tracking issue to track this and hopefully address it there. Will update the thread if we are able to address this in libtiledb.
