### ISSUE TITLE
ArrowInvalid

### ISSUE THREAD

**Issue by Material-Scientist** [TileDB-Inc/TileDB-Py#666]
I have a dataset that returns the following error message only if use_arrow=True in the TileDB query:

`ArrowInvalid: Column 2 named timestamp expected length 749418 but got length 749419`

data (~800MB):
https://1drv.ms/u/s!ArP7_EkyioIBxvQv96cE9oXibDU8YA?e=XWsSFo 

code that produces the error:

```
uri = os.path.join(Path(r'your_directory'),'derivative_ticker')

with tiledb.open(uri,'r') as A:
    print(A.schema)
    data = A.query(use_arrow=True).df[:,:,slice(None,np.datetime64('2019-12'))]

data
```

output:
![image](https://user-images.githubusercontent.com/40465719/132952933-5f33a5fd-102b-4ba2-b9b3-5bd1ca1ecc0c.png)

Using use_arrow=False  instead, results in a successful query:
![image](https://user-images.githubusercontent.com/40465719/132953003-a2afb76d-3f0e-4875-b8fe-9ac9f91c09fc.png)

I'm using TileDB version 0.10.0 for Python on Windows, and also made sure to update to the latest version of pyarrow.

**Comment by ihnorton** [comment]
Hi @Material-Scientist, thanks for opening the issue. Did this work with earlier versions of tiledb/tiledb-py?

**Comment by Material-Scientist** [comment]
> Hi @Material-Scientist, thanks for opening the issue. Did this work with earlier versions of tiledb/tiledb-py?

With versions [0.9.5, 0.9.4, 0.9.3] I can't even open the array:

`TileDBError: [TileDB::IO] Error: Cannot read from file 'array_path\derivative_ticker\__array_schema.tdb'; File opening error`

Upgrading back to 0.10.0 makes the array readable again, but only with use_arrow=False.

**Comment by ihnorton** [comment]
Thanks, I reproduced the issue. We will debug and get a fix out soon, but a quick work-around for now is to use the following before any other calls (this sets the initial buffer size to be large enough to complete in a single query):

```
tiledb.default_ctx({'py.init_buffer_bytes': 5*1024**3})
```

**Comment by Material-Scientist** [comment]
That worked, thanks!
