### ISSUE TITLE
Error when writing pandas dataframe

### ISSUE THREAD

**Issue by sixy6e** [TileDB-Inc/TileDB-Py#704]
Hi,

I ran into an issue in trying to write a sparse array to a private S3 bucket.

```
 File "/home/user/.local/lib/python3.9/site-packages/tiledb/dataframe_.py", line 428, in from_pandas
    schema = tiledb.ArraySchema.load(uri)
  File "tiledb/libtiledb.pyx", line 3431, in tiledb.libtiledb.ArraySchema.load
  File "tiledb/libtiledb.pyx", line 525, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 510, in tiledb.libtiledb._raise_tiledb_error
tiledb.libtiledb.TileDBError: [TileDB::S3] Error: Error while listing with prefix 's3://<bucket>/blah-blah/my-array.tiledb/__schema/' and delimiter '/'
```

TileDB version:

* tiledb.__version__
  * '0.10.1'
* tiledb.libtiledb.version()
  * (2, 4, 0)

The schema gets created with no problem, but failure happens when I later go to write using the `append` mode.

I suspect it has to do with this [line](https://github.com/TileDB-Inc/TileDB-Py/blob/dev/tiledb/dataframe_.py#L428), as the context doesn't get passed through when attempting to read the schema.

My quick fix in changing:

```python
schema = tiledb.ArraySchema.load(uri)
```
to
```python
schema = tiledb.ArraySchema.load(uri, ctx=tiledb_args.get("ctx"))
```

resolved the issue.

I don't know if this is the root of the problem, but I can try cooking up a minimal example if required?

**Comment by nguyenv** [comment]
Thanks for bringing this to our attention. I can't seem to reproduce this issue on my end. Can you post your minimal example?

**Comment by nguyenv** [comment]
You can disregard the previous comment. I had my AWS credentials set in `~/.aws/credentials`, so it was automatically picking that up and did not need a separate `Ctx` passed in. I have reproduced the issue, and we will get to fixing it soon.
