### ISSUE TITLE
github links in README not quite right

### ISSUE THREAD

**Issue by phaverty** [TileDB-Inc/TileDB-Py#73]
https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/quickstart_dense.py
gets you the HTML version

I think you want
https://rawgithub.com/TileDB-Inc/TileDB-Py/blob/dev/examples/quickstart_dense.py
for the TXT version

This is probably true in other docs too.

**Comment by ihnorton** [comment]
Fixed by https://github.com/TileDB-Inc/TileDB-Py/pull/132
