### ISSUE TITLE
Allow optional schema argument(s) for `from_numpy` method

### ISSUE THREAD

**Issue by tdenniston** [TileDB-Inc/TileDB-Py#77]
This would be convenient for creating a TileDB array from a Numpy array while still allowing for control over tile extents, compressors, etc. We could either allow passing a schema object, or instead individual arguments to control aspects like the tile extents.

**Comment by ihnorton** [comment]
I believe this is implemented (re-open if further refinement needed?):

[`static from_numpy(Ctx ctx, uri, ndarray array, **kw)`](https://docs.tiledb.io/projects/tiledb-py/en/latest/python-api.html#tiledb.DenseArray.from_numpy)
> **kw – additional arguments to pass to the DenseArray constructor

e.g.

```
import tiledb, numpy as np, tempfile
with tempfile.TemporaryDirectory() as tmp:
    # Creates array 'array' on disk.
    A = tiledb.DenseArray.from_numpy(tmp + "/array",  np.array([1.0, 2.0, 3.0]), tile_order='F', cell_order='F', coords_filters=FilterList([GzipFilter()
]))

>>> A.schema.dump()
- Array type: dense
- Cell order: col-major
- Tile order: col-major
- Capacity: 10000
- Coordinates compressor: GZIP
- Coordinates compression level: -1
...
```
