### ISSUE TITLE
Conda Packaging 

### ISSUE THREAD

**Issue by jakebolewski** [TileDB-Inc/TileDB-Py#8]
Make a conda recipe for building tiledb-py with libtiledb as a dependency, build and host binary images on Linux64, OSX, and Windows.

**Comment by jakebolewski** [comment]
Linux / OSX packages are up: https://github.com/conda-forge/tiledb-py-feedstock

Windows packages are blocked by: https://github.com/TileDB-Inc/TileDB/issues/417

**Comment by ihnorton** [comment]
Windows packages are available for 0.3.1.
